In [20]:
import numpy as np
import random

Crea un array de 10 números aleatorios enteros entre 0 y 100.

In [4]:
print(np.array(np.random.randint(1,100,10)))

[48 44 14 48 44 79 95 62 51 25]


Crea un array de 5 números aleatorios decimales entre 0 y 1.

In [8]:
print(np.array(np.random.rand(5)))

[0.64948936 0.58577036 0.24151983 0.3840294  0.24267586]


Crea dos arrays de números aleatorios enteros de longitud 5 y concaténalos.

In [16]:
a=np.array(np.random.randint(1,10,5))
b=np.array(np.random.randint(1,10,5))
print(a,b)
print(f"Array´s concatenados: {np.concat((a,b))}")

[8 5 7 4 6] [6 3 4 7 3]
Array´s concatenados: [8 5 7 4 6 6 3 4 7 3]


Crea un array de 10 números aleatorios enteros y sepáralo en dos arrays de 5 elementos cada uno.

In [ ]:
a=np.array(np.random.randint(1,20,10))
print(np.split(a,2))

[array([ 5, 13, 18,  2,  4], dtype=int32), array([ 5, 12,  8, 12, 16], dtype=int32)]


Crea una matriz de 3x3 con números aleatorios decimales entre 0 y 1.

In [19]:
print(np.array(np.random.rand(3,3)))

[[0.3983601  0.62536033 0.6038297 ]
 [0.55194619 0.21104843 0.52939738]
 [0.58643124 0.14000011 0.92429009]]


Crea un array de 10 números aleatorios enteros y selecciona 3 elementos al azar.

In [23]:
a=np.array(np.random.randint(1,300,10))
print(f"Elementos Seleccionados al azar: {np.random.choice(a,3)}")

Elementos Seleccionados al azar: [121 194  28]


Crea un array de 10 números aleatorios enteros entre 0 y 100 y calcula la media.

In [24]:
a=np.array(np.random.randint(0,100,10))
print(f"Media del array: {np.mean(a)} ")

Media del array: 40.5 
